im_model:
  num_reps: 100
  L: 2000000        # 2 Mb
  mu: 1.5e-8
  r_per_bp: 1.5e-8
  n_per_pop: 10
  num_rbins: 16

  sim_dir: "IM_model_simulations"
  trad_ld_dir: "traditional/LD_stats"
  trad_results_dir: "traditional/MomentsLD_results"
  gpu_ld_dir: "GPU/LD_stats"
  gpu_results_dir: "GPU/MomentsLD_results"
